### ISSUE TITLE
The LICENSE file is missing

### ISSUE THREAD

**Issue by ghost** [pia-foss/mobile-android-legacy#1]
Hello PIA Team,

I've noticed the [LICENSE](https://github.com/pia-foss/android/blob/master/LICENSE.md) file is missing in your Android PIA VPN app repository.

So I can't update the related Wikipedia [article](https://en.wikipedia.org/wiki/Private_Internet_Access) about your service. Could you fix it?

Thank you in advance,

Regards.

**Comment by ueshiba** [comment]
Hello, 

Thank you for reporting the issue, we missed to include the file at some point in the initial release. The source code is licensed under the GPLv3 and we will update the LICENSE file today.

Regards,
Jose

**Comment by ueshiba** [comment]
https://github.com/pia-foss/android/pull/2
