### ISSUE TITLE
Remove the repetitive warning "not possible to establish a connection to the VPN always enabled" when opening the app

### ISSUE THREAD

**Issue by andreldmonteiro** [pia-foss/mobile-android-legacy#10]
I have to deal with this PIA VPN warning everyday and it's getting tiresome, the VPN stays disabled until I open PIA and I have to click on this warning everytime I want to enter the app for it to auto-connect.

**Comment by kp-juan-docal** [comment]
@andreldmonteiro is this still an issue on version `3.19.2`?

**Comment by andreldmonteiro** [comment]
Hi, I don't know.

**Comment by kp-juan-docal** [comment]
In that case, I'll close this one given that it was reported on an old version. But please feel free to open a new issue if needed! 🙇
