### ISSUE TITLE
Rotation has stopped working on ChromeOS

### ISSUE THREAD

**Issue by kjperkin** [pia-foss/mobile-android-legacy#11]
# System Information
## Android
Android 9.x on ChromeOS

## ChromeOS
Google Chrome | 88.0.4324.208 (Official Build) (64-bit)
Revision | 1884b7e8b607ede8072319ce1bf841d628aa79bd-refs/branch-heads/4324@{#2251}
Platform | 13597.105.0 (Official Build) stable-channel caroline
Firmware Version | Google_Caroline.7820.384.0
Customization ID | SAMSUNG-CAROLINE
ARC | 7116332

## PIA App
v3.10.3

## Last Working Version
I'm unsure. I think it broke more than a month ago. I tolerated it for some time, but am fed up. I might try to bisect this weekend to help find the first broken commit.

# Expected Behavior
With Chromebook in "tablet mode" and rotated to landscape orientation, PIA app is usable in landscape orientation (either resizes to fill screen in landscape mode and allows scrolling, or maintains the portrait aspect ratio by letterboxing).

# Actual Behavior
Loading screen respects device orientation
Once loading screen goes away, the application forces the screen into portrait orientation even if the device is in landscape orientation, so PIA is "sideways".

## Screenshot
![pia-rotation-issue](https://user-images.githubusercontent.com/3441711/112425730-cbdafc80-8cf3-11eb-928f-7384f61e7cc1.png)

**Comment by jaspws** [comment]
Hey there,

So, I completely understand your frustration, and you may not love my answer but here it is. As it currently stands, we don't support landscape orientations - this has been true for a while, though we only recently disabled it all together in a recent update.

I'm glad that it happened to work well for you on your Chromebook, but unfortunately it did not work so well on the majority of devices we support.

We hope to support landscape in the future. For now, it would be relatively simple to build the project on your own and resolve this issue for yourself, but again, it's not really something we're going to introduce until we can make it work well on the majority of devices.

**Comment by kjperkin** [comment]
In app/src/main/java/com/privateinternetaccess/android/ui/superclasses/BaseActivity.java#onCreate() I see
```
if (!PIAApplication.isAndroidTV(this)) {
    setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
}
````

If instead this were:
```
if (!PIAApplication.isAndroidTV(this) && !PIAApplication.isChromebook(this)) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
        // Portrait, but allowed to switch between normal and reverse portrait.
        // Respect orientation lock as long as it is locked to a portrait orientation.
        setRequestedOrientation(SCREEN_ORIENTATION_USER_PORTRAIT);
    } else {
        // Forced to portrait. No support for holding the device "upside-down" in a portrait orientation
        // Makes application very difficult to use on chromebooks
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
    }
}
```

Then Chromebooks would be allowed to have landscape orientation and any other reasonably recent device would allow rotation that respects the actual orientation of the device (as long as it is in portrait mode).

If I'm lying in bed or on the couch resting my Chromebook on my chest in portrait orientation, then the power and volume buttons are on the "bottom" edge of the screen. In that position, it is far too easy to accidentally lock the device or even power it off.

**Comment by kp-juan-docal** [comment]
Hello @kjperkin I've created a ticket in our backlog to look into this. We will update this once we look into it.

**Comment by kp-juan-docal** [comment]
Hi @kjperkin our `3.21.0` release coming next week should be showing the application on potrait mode as expected. I'll go ahead and mark this one as resolved, but please feel free to open new issues if needed. Thanks!
