### ISSUE TITLE
A problem occurred evaluating project ':app'. > app\src\main\assets\regions.json (The system cannot find the path specified)

### ISSUE THREAD

**Issue by linmq** [pia-foss/mobile-android-legacy#12]
Just clone this project, open it on Android Studio, anybody know how to fix this? Thanks.

![image](https://user-images.githubusercontent.com/1535374/120741248-4790cb00-c527-11eb-9f58-7ab3fae6d596.png)

**Comment by kp-juan-docal** [comment]
Hi @linmq first of all apologies for the unforgivable delay in getting back to you. Is this still an issue. That file should be created as part of the build process as seen [here](https://github.com/pia-foss/android/blob/master/app/build.gradle#L267).
