### ISSUE TITLE
App seems to misinterpret packet loss or mobile/wifi handover as a disconnect when using WireGuard

### ISSUE THREAD

**Issue by triffid** [pia-foss/mobile-android-legacy#13]
I get constant reconnects with PIA Android when using WireGuard seemingly due to packet loss or mobile/wifi handover.

WireGuard is a connectionless protocol with IP rehoming built in, so packet loss during rekeying or public IP changes should not cause disconnect events.

The official WireGuard app has no such issue when connected to PIA's service, and I've had a stable connection ever since I switched 2 weeks ago.

The only issue with the official WireGuard app is I don't have the capacity to ping your API to set up peer configuration from my phone, so if my phone goes offline for a while or your server reboots I'll get stuck.

**Comment by triffid** [comment]
Fwiw, I'm _still_ using the Wireguard app on my phone since there's been no response to this issue - and it _still_ works just fine :P

**Comment by kp-juan-docal** [comment]
Hello @triffid apologies for the very late reply. Is this still an issue for you on `3.19.2`? If that's the case would you mind providing us with the steps so we have more or less an idea of the scenario you are facing? thanks! 🙇
