### ISSUE TITLE
Cannot Bypass VPN with System Setting Enabled.

### ISSUE THREAD

**Issue by Penguin-Guru** [pia-foss/mobile-android-legacy#14]
The setting "Allow LAN Traffic" does not seem to work when the system setting to "Block connections without VPN" is enabled. My first impression was that this made sense, but apparently that system setting should not prevent this app setting from working ([see here](https://github.com/GrapheneOS/os-issue-tracker/issues/638)). Is this a known issue? I noticed a similar issue for the Windows client [here](https://www.reddit.com/r/PrivateInternetAccess/comments/k4z29m/allow_lan_traffic_broken/), but it is from some time ago. My understanding is that the setting to Allow LAN Traffic should allow connections to local resources to be routed without the V.P.N., please correct me if that is wrong.

**Comment by kp-juan-docal** [comment]
hello @Penguin-Guru first of all, apologies for the very late reply! Unfortunately, we don't have control on how Android handles the "Block connections without VPN". From a VPN perspective we are allowing for those local connections to not go through the tunnel, but my guess is that the OS doesn't make any exceptions and block any connection attempt regardless of the destination. I hope this answers your question.
