### ISSUE TITLE
Request: Per-app settings: allow vpn, bypass vpn, and block internet completely

### ISSUE THREAD

**Issue by tdbe** [pia-foss/mobile-android-legacy#15]
Most phone brands are spying dicks and remove the android options to stop app data usage (foreground and background). The only alternative is to use VPN firewalls. But we also need PIA. So would it be difficult to implement a simple internet blocking toggle in PIA's per-app-settings menu?

I don't want my keyboard app to ever talk to the internet for example :)

**Comment by ueshiba** [comment]
Hi, this sounds like a firewall feature that we currently don't plan on implementing into PIA. Even if you use our VPN other apps can send data through it, and while the exit-point would be anonymized through our servers, there might be other identifying information. As such it's best to look for a third-party firewall app.

**Comment by tdbe** [comment]
> Hi, this sounds like a firewall feature that we currently don't plan on implementing into PIA. Even if you use our VPN other apps can send data through it, and while the exit-point would be anonymized through our servers, there might be other identifying information. As such it's best to look for a third-party firewall app.

You are unwittingly asking customers to stop using PIA. You don't seem to notice that NOBODY can use YOUR PIA VPN and also OTHER FIREWALLS (which can only work through the VPN functionality). 

You don't need firewall filtering features. You just need a simple per app on/off data switch which should be trivial to simply not forward the traffic.

The only recommended solution to this on XDA etc. is to not use a VPN (such as PIA) in favor of using a firewall "VPN" instead + use a tor browser like brave or orfox. So good job cutting out your market share. ☹✌

**Comment by privetryan** [comment]
@tdbe I agree with the report there's just no way in most non-root Android phones to have both VPN and blocking of apps' internet access completely at the same time. To be fair, this is not specific to PIA though. Some apps are secretly connecting and sending data to external endpoints without user's knowledge. This should be easy to implement if PIA devs understand the problem and the use case. This is not a rocket science to implement, they just need decision to proceed.

**Comment by tdbe** [comment]
To be clear:
1. you can in Android settings even Block connections that are NOT going through VPN. ✔
2. thus, if PIA/your vpn is not connected, 0 apps get access to internet. ✔
3. all you need now, is PIA to allow only some apps through the tunnel, the rest will be blocked ✔ (but ideally just redirect the blocked ones to 127.0.0.1 so you don't need to rely on 1. (because you might actually need e.g. netflix to bypass vpn sometimes))

Indeed can't believe it's "hard to understand".

**Comment by kp-juan-docal** [comment]
Hello @tdbe and everyone! Apologies for joining the conversation late. The behavior you describe can be achieved with a combination of the kill switch and per-app settings.

1. That is correct. You can achieve that by enabling the kill switch on Android (`Block connections without VPN`).
2. Yeah, same as your previous point. You can achieve it with that setting.
3. This one is where the per-app settings come into play. By excluding applications from going through the tunnel in combination with the `Block connections without VPN` option. You are blocking that application from the internet when the VPN is connected.

A few things might be relevant to the conversation.

1. The list of applications shown on the per-app settings list is all of the applications holding INTERNET permission, as you can see [here](https://github.com/pia-foss/android/blob/master/app/src/main/java/com/privateinternetaccess/android/utils/PerAppSettingsUtils.kt#L10).
2. We don't have granular access to traffic from particular applications. We can only tell the Android service which packages (applications) go [through the tunnel](https://developer.android.com/reference/android/net/VpnService.Builder#addAllowedApplication(java.lang.String)) and [which do not](https://developer.android.com/reference/android/net/VpnService.Builder#addDisallowedApplication(java.lang.String)).

I hope this information is useful to everyone involved.

**Comment by privetryan** [comment]
Hi @kp-juan-docal,

Thanks for the reply but did you even try your suggestion yourself? And will it work if you allow LAN connections? 
1. LAN connections
2. Direct connections

Because based on my testing it will completely block the connections of the above. What I and @tdbe requested is totally block but not including the legit direct and LAN connections.

Try that yourself and see if it will work.

**Comment by kp-juan-docal** [comment]
hey @privetryan, I did indeed test it for the steps I'm recommending above. I'll leave a recording here for future reference. Thanks!

https://github.com/pia-foss/mobile-android/assets/109512072/f9864232-7bd2-42c4-b71a-6c4839967c06
EDIT: Redacted IP

Now, to answer your other points.

1. No, it will block LAN connections as LAN connections don't go through the VPN tunnel and the kill switch blocks everything that doesn't go through the tunnel.
2. I'm assuming that by Direct connections you mean connections skipping the VPN tunnel. Same as above, it wouldn't work as the kill switch blocks everything that doesn't go through the tunnel.

Thanks!

**Comment by privetryan** [comment]
Hi @kp-juan-docal,

Thanks for the confirmation that both LAN and direct (yes you're correct I'm referring to skipping VPN) will be blocked if `Block connections without VPN` is on.
As you can see can't really use the VPN to just completely block suspicious apps with internet permission while still allowing legit apps to access LAN/skip VPN.

I understand even other VPNs behave like this but would be good to consider, maybe a tristate (direct,vpn,block) instead of just toggle. Then internally will use like a blackhole impl to just block and the other same as current to use/skip vpn.
