### ISSUE TITLE
Request: Make the PIA apk available in f-droid.org

### ISSUE THREAD

**Issue by sifr01** [pia-foss/mobile-android-legacy#16]
Seeing as this app is FOSS, it would be great if it was available on the f-droid.org app/repository. Iv seen that other (not as good ;-) VPN service providers have their apps on f-droid.

**Comment by ueshiba** [comment]
Hello @sifr01 

You can download the APK directly from our website https://www.privateinternetaccess.com/download/android-vpn-app (at the bottom of the page) or here: https://installers.privateinternetaccess.com/download/pia-android-3.12.2-10569.apk

But def we will consider your proposal! 

Regards

**Comment by bingoxo** [comment]
any update on this ?

**Comment by sifr01** [comment]
The [PIA changelog](https://www.privateinternetaccess.com/pages/changelog) doesnt provide checksums for PIA's android app releases. Whereas if the android app was made available in Fdroid, PGP signatures of the apk would be made available as a form of verification to mitigate against MiTM attacks.

**Comment by kp-juan-docal** [comment]
Closing it as a duplicate of the previous one https://github.com/pia-foss/android/issues/4
