### ISSUE TITLE
Website doesnt show latest apk for download

### ISSUE THREAD

**Issue by sifr01** [pia-foss/mobile-android-legacy#17]
The [main download page of the website](https://www.privateinternetaccess.com/download/android-vpn-app) offers version [3.12.2-10569](https://installers.privateinternetaccess.com/download/pia-android-3.12.2-10569.apk) for download whereas the app informs me and directs me to [this page on the website](https://www.privateinternetaccess.com/installer/download_installer_android) which correctly offers me [the latest version 3.12.3-10570](https://installers.privateinternetaccess.com/download/pia-android-3.12.3-10570.apk). 

Please can you update the [main download page of the website](https://www.privateinternetaccess.com/download/android-vpn-app) to provide the most up to date version of the PIA apk (3.12.3-10570).

**Comment by kp-juan-docal** [comment]
hello @sifr01 as I've mentioned to others. Apologies for the unforgivable delay on replying to you. We will be keeping a closer look on issues reported here, so please keep them coming. That being said, this has now been resolved. I'll go ahead and close this as resolved.
