### ISSUE TITLE
UI shows orange turn on-off switch when connected to the VPN

### ISSUE THREAD

**Issue by archerallstars** [pia-foss/mobile-android-legacy#19]
When I connected to the VPN, the main UI still shows the orange switch which should only be showed when the user doesn't connect to the VPN. This issue can be seen in the screen recording below:

https://user-images.githubusercontent.com/1403194/146995853-7090f27a-9b18-4931-ab51-f5f7c8b4012f.mp4

### My device info:

- Lenovo Tab P11, TB-J606L
- Android 11
- PIA version: 3.12.4 (571) - playstore

**Comment by kp-juan-docal** [comment]
hello @kreaninw apologies for the very late reply! Is this something you can still reproduce on version `3.19.2`?

**Comment by archerallstars** [comment]
> hello @kreaninw apologies for the very late reply! Is this something you can still reproduce on version `3.19.2`?

Thanks! Sorry, I can't test this issue at the moment because I moved to another service 🙏

**Comment by kp-juan-docal** [comment]
I understand. Thank you for taking the time to reply and report it in the first place!
