### ISSUE TITLE
VPN causes network to report as metered

### ISSUE THREAD

**Issue by Liam2349** [pia-foss/mobile-android-legacy#20]
Hello, I think my email chain with support has bugged out as it has sent me a survey asking me to rate my support experience, but the problem has not been solved or even acknowledged thus far.

I develop software and in one of my programs, I noticed that my connection was reporting as metered. I debugged this issue and found that this only occurs when the PIA app is connected.

I did further googling and found that in Android 11 or Android 12, a change was made which causes this, and that VPN apps need to update in some way to avoid this effect. I would like for whoever makes the mobile app to resolve this issue, as some of your competitors have reportedly done already.

To help, I have produced an open-source reproduction project, which I already provided to PIA support: https://github.com/Liam2349/Android12MeteredVPNRepro

See the instructions inside, and conveniently access the built APK here for testing: https://github.com/Liam2349/Android12MeteredVPNRepro/releases/tag/Release

The reproduction is very simple and there are instructions over on github. When the PIA app is connected, the native Android.Net.ConnectivityManager.IsActiveNetworkMetered method reports metered, and when the PIA app is not connected, it reports unmetered as it should for my network.

I hope to see a resolution to this issue soon. Please note that this affects Android 12, perhaps Android 11 also, but not Android 10.

Also on reddit: https://www.reddit.com/r/PrivateInternetAccess/comments/tesnzi/androidbug_vpn_causes_network_to_report_as_metered/

**Comment by Mijail** [comment]
Hey Liam! Thank you very much for all the useful information here, we took a look into it and we are adding it to our next developments, expect this in a couple releases! Thank you again.

**Comment by Liam2349** [comment]
Hello, I don't see you as part of this repository, but in the case that you are a PIA employee, that is great news and I look forward to a fix!

**Comment by kp-juan-docal** [comment]
hello @Liam2349 first of all, apologies for the very late reply. Is this something you can still reproduce with our latest version? I just did a quick test using Android 11 and `IsActiveNetworkMetered` returns `false` when the VPN is connected for both OpenVPN and Wireguard.
