### ISSUE TITLE
Request: enabling the VPN in app or via quick panel should override automation

### ISSUE THREAD

**Issue by ghost** [pia-foss/mobile-android-legacy#21]
When having automation disable the VPN it isn't possible to manually enable the VPN without disabling automation. There should be a way to override that with manual intervention

**Comment by ghost** [comment]
This can also apply to pia-ios

**Comment by kp-juan-docal** [comment]
hello @cardcraft apologies for the very late reply. I've created a ticket in our backlog to look into it. We will update this once we have done so.

**Comment by ghost** [comment]
Sounds good, Thanks

**Comment by ghost** [comment]
At the moment i've just disabled the automation and done it manually.

**Comment by kp-juan-docal** [comment]
Hi @cardcraft our `3.21.0` android release coming next week should address this. In app user actions on the connection state will take priority over automation rules. I'll proceed to close this ticket as resolved, but please feel free to create new ones if needed. Thanks!
