### ISSUE TITLE
keep adding releases and changelogs

### ISSUE THREAD

**Issue by piramiday** [pia-foss/mobile-android-legacy#3]
I can see that the last commit, b027493112f80bb8e8967ac16ca0772d90d911c4, pushed from 3.2.0 to 3.5.1.

could you please push each release _individually_, together with an explicit **changelog**?

for example, [PIA's website](https://www.privateinternetaccess.com/installer/download_installer_android) at present is offering version 3.5.4.

**Comment by ueshiba** [comment]
Hello @piramiday 

Thank you for the message! Yes, I agree with you that we have to improve our release process here. We are going to start to push every release here as soon as the rollout in Google Play is complete. 

I hope this could help your experience using our public repository.

Regards,
Jose Blaya

**Comment by piramiday** [comment]
is there a changelog for release 3.6.1? 0377c6de52b46899da0616735af25031fccd8704
