### ISSUE TITLE
Android app with MACE asks for payment even with an active subscription

### ISSUE THREAD

**Issue by mystic-githuber** [pia-foss/mobile-android-legacy#9]
Android app with MACE asks for payment even with an active monthly subscription, then logs-out the account when declining to pay with the VPN sill connected. 

This behavior doesn't manifest on the play-store variant. 

PIA with MACE Version 3.9.1.
Android OS version 9

**Comment by jaspws** [comment]
Hey there,

We've made a few attempts at replicating your issue but can't seem to make it happen on our end. Would you be able to provide a little more information to help us out here?

When it "asks for payment" could you let us know exactly what the dialog says (assuming it's a dialog).
What are the exact steps to get this to pop-up? For example, does it happen after trying to connect to a server, when you launch the app, etc.

If you can let us know those two things we can dig a little deeper into this and hopefully reproduce it and resolve the issue.

**Comment by mystic-githuber** [comment]
@jaspws 

Sure, let me give you more information about my OS. I am running Lineage OS based on android 9 with microg to get notifications. My bootloader is unlocked but my ROM is not rooted.

I can't recall the exact text about the notification because now it has auto-renewed my subscription. The text notification pop's up below the status bar a few days before my renewal period asking to renew my payment and all this time I am connected to your service. If I just clear the notifications without tapping on it, everything proceeds as usual but I I tap on it, it opens open the app asking me for renewal and then when declining the payment as I mentioned before it locks me out without logging me out of the service.

This notification appears twice before the renewal period comes to pass.

**Comment by jaspws** [comment]
Thanks for that info. I just have one more question.

You mentioned the issue happened on the MACE build, but did you happen to have an account purchased through the Play Store? If that's the case, it's very very unlikely you'll experience this issue again and we're pretty sure it's already been resolved.

**Comment by mystic-githuber** [comment]
@jaspws 
I created an account last spring via the website with a monthly subscription. I didn't know till December last year that you had builds with MACE in it. I switched to it and experienced the bug.
